openapi: 3.0.3
info:
  title: Dashboard
  description: >
    Describes the operations and schemas for Dashboard
  version: 1.0.11
servers:
  - url: http://localhost:4301/api/v0
tags:
  - name: user
    description: user related routes
paths:
  /users:
    get:
      tags:
        - user
      summary: Fetch all users
      description: Fetch all users
      responses:
        '200':
          $ref: '#/components/responses/Users'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '413':
          $ref: '#/components/responses/PayloadTooLargeError'
        '500':
          $ref: '#/components/responses/ServerError'
        '504':
          $ref: '#/components/responses/GatewayTimeoutError'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - dateOfBirth
        - address
        - phone
      properties:
        id:
          type: string
          format: uuid
          example: adb3271f-94dc-4169-80e9-3d4c8a90201f
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
        address:
          type: string
        phone:
          type: string
          format: phone
  responses:
    User:
      description: A user object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    Users:
      description: An array of user objects
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
    InvalidInputError:
      description: Invalid input supplied by the client
    NotFoundError:
      description: Requested entity not found
    ConflictError:
      description: Requested entity already exists
    PayloadTooLargeError:
      description: Requested payload is too large
    ServerError:
      description: Server related error
    GatewayTimeoutError:
      description: An external service did not respond in time
