version: "3.9"
services:
  smc-cypress:
    container_name: smc-cypress
    restart: "no"
    build:
      context: ../fe
      dockerfile: Dockerfile
      target: fe-test
      args:
      - HOST_UID=499
      - HOST_GID=999
    user: 499:999
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      # Volume source code
      - ../fe/src:/home/testUser/src:rw
      - ../fe/cypress:/home/testUser/cypress:rw
      # Volume X11-unix socket, allows the host to display GUI of a process
      # which runs inside a docker container
      - /tmp/.X11-unix:/tmp/.X11-unix
    # A must for X11 to work
    network_mode: "host"
    # Override the entry point script to allow passing cypress flags
    entrypoint: cypress open --project /home/testUser --env mode=${MODE}