version: "3.9"

services:
  db-pg-dev:
    hostname: db-pg-dev
    container_name: db-pg-dev
    restart: unless-stopped
    image: postgres:16.1-alpine
    user: ${UID}:${GID}
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db-dev
    volumes:
      - ../db-dev-data:/var/lib/postgresql/data:rw
      # See: https://github.com/docker-library/docs/blob/master/postgres/README.md#arbitrary---user-notes
      - /etc/passwd:/etc/passwd:ro
    stop_grace_period: 2s
    healthcheck:
      test: pg_isready -p 5432 -U admin -d db-dev
      interval: 3s
      timeout: 2s
      retries: 5
    command: postgres -p 5432

################################################################################

  db-pg-test:
    hostname: db-pg-test
    container_name: db-pg-test
    restart: unless-stopped
    image: postgres:16.1-alpine
    user: ${UID}:${GID}
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db-test
    stop_grace_period: 2s
    healthcheck:
      test: pg_isready -p 5432 -U admin -d db-test
      interval: 3s
      timeout: 2s
      retries: 5
    command: postgres -p 5432

################################################################################

  db-be-dev:
    container_name: db-be-dev
    restart: unless-stopped
    user: ${UID}:${GID}
    build:
      context: ../be
      dockerfile: Dockerfile
      target: be-dev
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ../be:/home/node/db:rw
    environment:
      - SERVER_PORT=2828
      - SERVER_DEBUG_PORT=2829
      - SERVER_URL=http://localhost
      - API_ROUTE=v0/api
      - HEALTH_CHECK_ROUTE=health
      - ALLOWED_HOSTS=localhost
      - ALLOWED_ORIGINS=*
      - NODE_ENV=development
      - DB_URI=postgres://admin:admin@db-pg-dev:5432/db-dev
      - DB_TEST_URI=postgres://admin:admin@db-pg-test:5432/db-test
    stop_grace_period: 2s
    ports:
      - 2828:2828
      - 2829:2829
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:2828/health | grep -q '204'"
        ]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 30s
    depends_on:
      db-pg-dev:
        condition: service_healthy
    command: npm run _start

################################################################################

  db-fe-dev:
    container_name: db-fe-dev
    restart: unless-stopped
    user: ${UID}:${GID}
    build:
      context: ../fe
      dockerfile: Dockerfile
      target: fe-dev
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ../fe:/home/node/db:rw
    stop_grace_period: 2s
    ports:
      - 5173:5173
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:5173 | grep -q '200'",
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 45s
    command: npm run _start
